services:
  zookeeper:
    image: ${IMAGE_PREFIX}confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: ${IMAGE_PREFIX}confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
      - ldap
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_SASL_CLIENT: "false"
      KAFKA_LISTENERS: PLAINTEXT://:9092,SASL_PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,SASL_PLAINTEXT://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # SASL/PLAIN mit LDAP-Anbindung, nÃ¶tige Konfig in server.properties
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_SUPER_USERS: User:admin

      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_PLAIN_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN

      # LDAP Authentifizierung
      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_PLAIN_SASL_SERVER_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.authenticator.TestingLdapLoginModule
      KAFKA_LDAP_URL: ldap://ldap:389
      KAFKA_LDAP_USER_DN_TEMPLATE: uid={0},ou=users,dc=acme,dc=org
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/kafka/jaas.conf
        -Dzookeeper.sasl.client=false

      #KAFKA_CUSTOM_INIT_SCRIPT: |
      #  if [ -f /etc/kafka/kafka/custom-server.properties ]; then
      #    cat /etc/kafka/kafka/custom-server.properties >> /etc/kafka/server.properties
      #  fi
    volumes:
      - ./kafka/jaas.conf:/etc/kafka/jaas.conf
      - ./kafka/custom-server.properties:/etc/kafka/kafka/custom-server.properties

  ldap:
    image: ${IMAGE_PREFIX}cleanstart/openldap:latest
    ports:
      - "10389:389"
    volumes:
      - ./openldap/data:/var/lib/openldap/openldap-data
      - ./openldap/conf/slapd.conf:/etc/openldap/slapd.conf
